import pygame

NUM_OF_ROW = 25
NUM_OF_COL = 50
AMOUNT_OF_GRASS = 20
BOX_SIZE = 25

GRASS_IMG = r'photos\grass.png'

WINDOW_WIDTH = NUM_OF_COL * BOX_SIZE
WINDOW_HEIGHT = NUM_OF_ROW * BOX_SIZE

BACKGROUND_COLOR = (38, 155, 38)

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3
PLAY_AGAIN_STATE = 4

SOLDIER_START_X = SOLDIER_START_Y = 0