import pygame

NUM_OF_ROW = 25
NUM_OF_COL = 50
AMOUNT_OF_GRASS = 20
BOX_SIZE = 25

GRASS_IMG = r"photos\grass.png"
SOLDIER_IMG = r"photos\soldier.png"
FLAG_IMG = r"photos\flag.png"

WINDOW_WIDTH = NUM_OF_COL * BOX_SIZE
WINDOW_HEIGHT = NUM_OF_ROW * BOX_SIZE

BACKGROUND_COLOR = (38, 155, 38)
VIEW_MINES_COLOR = (0, 0, 0)

SOLDIER_WIDTH = 2
SOLDIER_HEIGHT = 4
SOLDIER_START_X, SOLDIER_START_Y = 0, 0
soldier_index = [SOLDIER_START_X, SOLDIER_START_Y]


FLAG_WIDTH = 4
FLAG_HEIGHT = 3
FLAG_LOCATION = [NUM_OF_COL - FLAG_WIDTH, NUM_OF_ROW - FLAG_HEIGHT]

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3
PLAY_AGAIN_STATE = 4